### PR TITLE
fix(filter): Make sure the file is accessible

### PR DESCRIPTION
**Pull request by knownasilya**
before checking that it's a directory

Resolves https://github.com/denali-js/denali-cli/issues/8

### CODE REVIEW

**Comment by knownasilya** [comment]
I added sum links to fixtures, supposedly they should be restored on clone.. no idea.

**Comment by davewasmer** [comment]
I don't see the test bad symlink file in the changed files - is it the `.gitkeep` file, and Github is just showing it as a regular file?

**Comment by knownasilya** [comment]
I symlinked `external` to node modules and an `external-invalid`, and then deleted the source folder.

**Comment by davewasmer** [comment]
I just checked it out locally and there's no symlinks in the `test` folder in this PR's branch. Are you on a Windows machine?

**Comment by davewasmer** [comment]
Alternatively, you could manually write the symlink when the tests run.

**Comment by knownasilya** [comment]
@davewasmer all set

**Pull request merged**
